name = "gxid"
version = "0.3.0"
licences = ["Apache-2.0"]
description = "A Gleam implementation of xid"
repository = { type = "github", user = "defgenx", repo = "gxid" }

gleam_version = ">= 1.0.0"

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_bitwise = "~> 1.3"
gleam_otp = "~> 0.10"
gleam_erlang = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 1.0"
